language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dev-i386
  # Install libclang.
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main" --yes
  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main"  --yes
  - sudo apt-get update
  - sudo apt-get install libclang1-8 libclang-common-8-dev  --yes --force-yes
  - sudo apt-get install clang-8  --yes --force-yes
  - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-8.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
  - sudo ldconfig

script:
  - ./deploy.sh
