MakeNameEx(LocByName("Storm_101"), "SNetCreateGame", SN_NOWARN)
MakeNameEx(LocByName("Storm_102"), "SNetDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_103"), "SNetEnumProviders", SN_NOWARN)
MakeNameEx(LocByName("Storm_104"), "SNetEnumDevices", SN_NOWARN)
MakeNameEx(LocByName("Storm_105"), "SNetEnumGames", SN_NOWARN)
MakeNameEx(LocByName("Storm_106"), "SNetDropPlayer", SN_NOWARN)
MakeNameEx(LocByName("Storm_107"), "SNetGetGameInfo", SN_NOWARN)
MakeNameEx(LocByName("Storm_108"), "SNetGetNetworkLatency", SN_NOWARN)
MakeNameEx(LocByName("Storm_109"), "SNetGetNumPlayers", SN_NOWARN)
MakeNameEx(LocByName("Storm_110"), "SNetGetOwnerTurnsWaiting", SN_NOWARN)
MakeNameEx(LocByName("Storm_111"), "SNetGetPerformanceData", SN_NOWARN)
MakeNameEx(LocByName("Storm_112"), "SNetGetPlayerCaps", SN_NOWARN)
MakeNameEx(LocByName("Storm_113"), "SNetGetPlayerName", SN_NOWARN)
MakeNameEx(LocByName("Storm_114"), "SNetGetProviderCaps", SN_NOWARN)
MakeNameEx(LocByName("Storm_115"), "SNetGetTurnsInTransit", SN_NOWARN)
MakeNameEx(LocByName("Storm_116"), "SNetInitializeDevice", SN_NOWARN)
MakeNameEx(LocByName("Storm_117"), "SNetInitializeProvider", SN_NOWARN)
MakeNameEx(LocByName("Storm_118"), "SNetJoinGame", SN_NOWARN)
MakeNameEx(LocByName("Storm_119"), "SNetLeaveGame", SN_NOWARN)
MakeNameEx(LocByName("Storm_120"), "SNetPerformUpgrade", SN_NOWARN)
MakeNameEx(LocByName("Storm_121"), "SNetReceiveMessage", SN_NOWARN)
MakeNameEx(LocByName("Storm_122"), "SNetReceiveTurns", SN_NOWARN)
MakeNameEx(LocByName("Storm_123"), "SNetRegisterEventHandler", SN_NOWARN)
MakeNameEx(LocByName("Storm_124"), "SNetResetLatencyMeasurements", SN_NOWARN)
MakeNameEx(LocByName("Storm_125"), "SNetSelectGame", SN_NOWARN)
MakeNameEx(LocByName("Storm_126"), "SNetSelectProvider", SN_NOWARN)
MakeNameEx(LocByName("Storm_127"), "SNetSendMessage", SN_NOWARN)
MakeNameEx(LocByName("Storm_128"), "SNetSendTurn", SN_NOWARN)
MakeNameEx(LocByName("Storm_129"), "SNetSetBasePlayer", SN_NOWARN)
MakeNameEx(LocByName("Storm_130"), "SNetSetGameMode", SN_NOWARN)
MakeNameEx(LocByName("Storm_131"), "SNetUnregisterEventHandler", SN_NOWARN)
MakeNameEx(LocByName("Storm_133"), "SNetEnumGamesEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_134"), "SNetSendServerChatCommand", SN_NOWARN)
MakeNameEx(LocByName("Storm_135"), "SNetSendDatagram", SN_NOWARN)
MakeNameEx(LocByName("Storm_136"), "SNetReceiveDatagram", SN_NOWARN)
MakeNameEx(LocByName("Storm_137"), "SNetDisconnectAll", SN_NOWARN)
MakeNameEx(LocByName("Storm_138"), "SNetCreateLadderGame", SN_NOWARN)
MakeNameEx(LocByName("Storm_139"), "SNetReportGameResult", SN_NOWARN)
MakeNameEx(LocByName("Storm_140"), "SNetCheckDataFile", SN_NOWARN)
MakeNameEx(LocByName("Storm_141"), "SNetSendLeagueCommand", SN_NOWARN)
MakeNameEx(LocByName("Storm_142"), "SNetSendReplayPath", SN_NOWARN)
MakeNameEx(LocByName("Storm_143"), "SNetGetLeagueName", SN_NOWARN)
MakeNameEx(LocByName("Storm_144"), "SNetGetPlayerNames", SN_NOWARN)
MakeNameEx(LocByName("Storm_145"), "SNetLeagueLogout", SN_NOWARN)
MakeNameEx(LocByName("Storm_146"), "SNetGetLeaguePlayerName", SN_NOWARN)
MakeNameEx(LocByName("Storm_150"), "Ordinal150", SN_NOWARN)
MakeNameEx(LocByName("Storm_151"), "Ordinal151", SN_NOWARN)
MakeNameEx(LocByName("Storm_201"), "SDlgBeginPaint", SN_NOWARN)
MakeNameEx(LocByName("Storm_202"), "SDlgBltToWindowI", SN_NOWARN)
MakeNameEx(LocByName("Storm_203"), "SDlgCheckTimers", SN_NOWARN)
MakeNameEx(LocByName("Storm_204"), "SDlgCreateDialogIndirectParam", SN_NOWARN)
MakeNameEx(LocByName("Storm_205"), "SDlgCreateDialogParam", SN_NOWARN)
MakeNameEx(LocByName("Storm_206"), "SDlgDefDialogProc", SN_NOWARN)
MakeNameEx(LocByName("Storm_208"), "SDlgDialogBoxIndirectParam", SN_NOWARN)
MakeNameEx(LocByName("Storm_209"), "SDlgDialogBoxParam", SN_NOWARN)
MakeNameEx(LocByName("Storm_210"), "SDlgDrawBitmap", SN_NOWARN)
MakeNameEx(LocByName("Storm_211"), "SDlgEndDialog", SN_NOWARN)
MakeNameEx(LocByName("Storm_212"), "SDlgEndPaint", SN_NOWARN)
MakeNameEx(LocByName("Storm_213"), "SDlgKillTimer", SN_NOWARN)
MakeNameEx(LocByName("Storm_214"), "SDlgSetBaseFont", SN_NOWARN)
MakeNameEx(LocByName("Storm_215"), "SDlgSetBitmapI", SN_NOWARN)
MakeNameEx(LocByName("Storm_216"), "SDlgSetControlBitmaps", SN_NOWARN)
MakeNameEx(LocByName("Storm_217"), "SDlgSetCursor", SN_NOWARN)
MakeNameEx(LocByName("Storm_218"), "SDlgSetSystemCursor", SN_NOWARN)
MakeNameEx(LocByName("Storm_219"), "SDlgSetTimer", SN_NOWARN)
MakeNameEx(LocByName("Storm_220"), "SDlgUpdateCursor", SN_NOWARN)
MakeNameEx(LocByName("Storm_221"), "SDlgBltToWindowE", SN_NOWARN)
MakeNameEx(LocByName("Storm_222"), "SDlgSetBitmapE", SN_NOWARN)
MakeNameEx(LocByName("Storm_223"), "SDlgSetLocale", SN_NOWARN)
MakeNameEx(LocByName("Storm_224"), "Ordinal224", SN_NOWARN)
MakeNameEx(LocByName("Storm_251"), "SFileAuthenticateArchive", SN_NOWARN)
MakeNameEx(LocByName("Storm_252"), "SFileCloseArchive", SN_NOWARN)
MakeNameEx(LocByName("Storm_253"), "SFileCloseFile", SN_NOWARN)
MakeNameEx(LocByName("Storm_254"), "SFileDdaBegin", SN_NOWARN)
MakeNameEx(LocByName("Storm_255"), "SFileDdaBeginEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_256"), "SFileDdaDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_257"), "SFileDdaEnd", SN_NOWARN)
MakeNameEx(LocByName("Storm_258"), "SFileDdaGetPos", SN_NOWARN)
MakeNameEx(LocByName("Storm_259"), "SFileDdaGetVolume", SN_NOWARN)
MakeNameEx(LocByName("Storm_260"), "SFileDdaInitialize", SN_NOWARN)
MakeNameEx(LocByName("Storm_261"), "SFileDdaSetVolume", SN_NOWARN)
MakeNameEx(LocByName("Storm_262"), "SFileDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_263"), "SFileEnableDirectAccess", SN_NOWARN)
MakeNameEx(LocByName("Storm_264"), "SFileGetFileArchive", SN_NOWARN)
MakeNameEx(LocByName("Storm_265"), "SFileGetFileSize", SN_NOWARN)
MakeNameEx(LocByName("Storm_266"), "SFileOpenArchive", SN_NOWARN)
MakeNameEx(LocByName("Storm_267"), "SFileOpenFile", SN_NOWARN)
MakeNameEx(LocByName("Storm_268"), "SFileOpenFileEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_269"), "SFileReadFile", SN_NOWARN)
MakeNameEx(LocByName("Storm_270"), "SFileSetBasePath", SN_NOWARN)
MakeNameEx(LocByName("Storm_271"), "SFileSetFilePointer", SN_NOWARN)
MakeNameEx(LocByName("Storm_272"), "SFileSetLocale", SN_NOWARN)
MakeNameEx(LocByName("Storm_273"), "SFileGetBasePath", SN_NOWARN)
MakeNameEx(LocByName("Storm_274"), "SFileSetIoErrorMode", SN_NOWARN)
MakeNameEx(LocByName("Storm_275"), "SFileGetArchiveName", SN_NOWARN)
MakeNameEx(LocByName("Storm_276"), "SFileGetFileName", SN_NOWARN)
MakeNameEx(LocByName("Storm_277"), "SFileGetArchiveInfo", SN_NOWARN)
MakeNameEx(LocByName("Storm_278"), "SFileSetPlatform", SN_NOWARN)
MakeNameEx(LocByName("Storm_279"), "SFileLoadFile", SN_NOWARN)
MakeNameEx(LocByName("Storm_280"), "SFileUnloadFile", SN_NOWARN)
MakeNameEx(LocByName("Storm_281"), "SFileLoadFileEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_282"), "SFilePrioritizeRequest", SN_NOWARN)
MakeNameEx(LocByName("Storm_283"), "SFileCancelRequest", SN_NOWARN)
MakeNameEx(LocByName("Storm_284"), "SFileSetAsyncBudget", SN_NOWARN)
MakeNameEx(LocByName("Storm_285"), "SFileSetDataChunkSize", SN_NOWARN)
MakeNameEx(LocByName("Storm_286"), "SFileEnableSeekOptimization", SN_NOWARN)
MakeNameEx(LocByName("Storm_287"), "SFileReadFileEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_288"), "SFileFileExists", SN_NOWARN)
MakeNameEx(LocByName("Storm_289"), "SFileFileExistsEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_290"), "SFileReadFileEx2", SN_NOWARN)
MakeNameEx(LocByName("Storm_291"), "SFileReadFile2", SN_NOWARN)
MakeNameEx(LocByName("Storm_292"), "SFileLoadFile2", SN_NOWARN)
MakeNameEx(LocByName("Storm_293"), "SFileOpenFileAsArchive", SN_NOWARN)
MakeNameEx(LocByName("Storm_294"), "SFileGetLocale", SN_NOWARN)
MakeNameEx(LocByName("Storm_295"), "SFileRegisterLoadNotifyProc", SN_NOWARN)
MakeNameEx(LocByName("Storm_296"), "SFileGetFileCompressedSize", SN_NOWARN)
MakeNameEx(LocByName("Storm_297"), "Ordinal297", SN_NOWARN)
MakeNameEx(LocByName("Storm_298"), "Ordinal298", SN_NOWARN)
MakeNameEx(LocByName("Storm_299"), "SFileAuthenticateArchiveEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_300"), "SFileOpenPathAsArchive", SN_NOWARN)
MakeNameEx(LocByName("Storm_301"), "StormDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_302"), "StormGetInstance", SN_NOWARN)
MakeNameEx(LocByName("Storm_303"), "StormGetOption", SN_NOWARN)
MakeNameEx(LocByName("Storm_304"), "StormSetOption", SN_NOWARN)
MakeNameEx(LocByName("Storm_312"), "SBltGetSCode", SN_NOWARN)
MakeNameEx(LocByName("Storm_313"), "SBltROP3", SN_NOWARN)
MakeNameEx(LocByName("Storm_314"), "SBltROP3Clipped", SN_NOWARN)
MakeNameEx(LocByName("Storm_315"), "SBltROP3Tiled", SN_NOWARN)
MakeNameEx(LocByName("Storm_321"), "SBmpDecodeImage", SN_NOWARN)
MakeNameEx(LocByName("Storm_323"), "SBmpLoadImage", SN_NOWARN)
MakeNameEx(LocByName("Storm_324"), "SBmpSaveImage", SN_NOWARN)
MakeNameEx(LocByName("Storm_325"), "SBmpAllocLoadImage", SN_NOWARN)
MakeNameEx(LocByName("Storm_326"), "SBmpSaveImageEx", SN_NOWARN)
MakeNameEx(LocByName("Storm_331"), "SCodeCompile", SN_NOWARN)
MakeNameEx(LocByName("Storm_332"), "SCodeDelete", SN_NOWARN)
MakeNameEx(LocByName("Storm_334"), "SCodeExecute", SN_NOWARN)
MakeNameEx(LocByName("Storm_335"), "SCodeGetPseudocode", SN_NOWARN)
MakeNameEx(LocByName("Storm_341"), "SDrawAutoInitialize", SN_NOWARN)
MakeNameEx(LocByName("Storm_342"), "SDrawCaptureScreen", SN_NOWARN)
MakeNameEx(LocByName("Storm_343"), "SDrawClearSurface", SN_NOWARN)
MakeNameEx(LocByName("Storm_344"), "SDrawDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_345"), "SDrawFlipPage", SN_NOWARN)
MakeNameEx(LocByName("Storm_346"), "SDrawGetFrameWindow", SN_NOWARN)
MakeNameEx(LocByName("Storm_347"), "SDrawGetObjects", SN_NOWARN)
MakeNameEx(LocByName("Storm_348"), "SDrawGetScreenSize", SN_NOWARN)
MakeNameEx(LocByName("Storm_349"), "SDrawGetServiceLevel", SN_NOWARN)
MakeNameEx(LocByName("Storm_350"), "SDrawLockSurface", SN_NOWARN)
MakeNameEx(LocByName("Storm_351"), "SDrawManualInitialize", SN_NOWARN)
MakeNameEx(LocByName("Storm_352"), "SDrawMessageBox", SN_NOWARN)
MakeNameEx(LocByName("Storm_353"), "SDrawPostClose", SN_NOWARN)
MakeNameEx(LocByName("Storm_354"), "SDrawRealizePalette", SN_NOWARN)
MakeNameEx(LocByName("Storm_355"), "SDrawSelectGdiSurface", SN_NOWARN)
MakeNameEx(LocByName("Storm_356"), "SDrawUnlockSurface", SN_NOWARN)
MakeNameEx(LocByName("Storm_357"), "SDrawUpdatePalette", SN_NOWARN)
MakeNameEx(LocByName("Storm_358"), "SDrawUpdateScreen", SN_NOWARN)
MakeNameEx(LocByName("Storm_359"), "SDrawWaitForVerticalBlank", SN_NOWARN)
MakeNameEx(LocByName("Storm_372"), "SEvtDispatch", SN_NOWARN)
MakeNameEx(LocByName("Storm_373"), "SEvtRegisterHandler", SN_NOWARN)
MakeNameEx(LocByName("Storm_374"), "SEvtUnregisterHandler", SN_NOWARN)
MakeNameEx(LocByName("Storm_375"), "SEvtUnregisterType", SN_NOWARN)
MakeNameEx(LocByName("Storm_376"), "SEvtPopState", SN_NOWARN)
MakeNameEx(LocByName("Storm_377"), "SEvtPushState", SN_NOWARN)
MakeNameEx(LocByName("Storm_378"), "SEvtBreakHandlerChain", SN_NOWARN)
MakeNameEx(LocByName("Storm_381"), "SGdiBitBlt", SN_NOWARN)
MakeNameEx(LocByName("Storm_382"), "SGdiCreateFont", SN_NOWARN)
MakeNameEx(LocByName("Storm_383"), "SGdiDeleteObject", SN_NOWARN)
MakeNameEx(LocByName("Storm_384"), "SGdiDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_385"), "SGdiExtTextOut", SN_NOWARN)
MakeNameEx(LocByName("Storm_386"), "SGdiImportFont", SN_NOWARN)
MakeNameEx(LocByName("Storm_387"), "SGdiLoadFont", SN_NOWARN)
MakeNameEx(LocByName("Storm_388"), "SGdiRectangle", SN_NOWARN)
MakeNameEx(LocByName("Storm_389"), "SGdiSelectObject", SN_NOWARN)
MakeNameEx(LocByName("Storm_390"), "SGdiSetPitch", SN_NOWARN)
MakeNameEx(LocByName("Storm_391"), "SGdiTextOut", SN_NOWARN)
MakeNameEx(LocByName("Storm_392"), "SGdi392", SN_NOWARN)
MakeNameEx(LocByName("Storm_393"), "Ordinal393", SN_NOWARN)
MakeNameEx(LocByName("Storm_399"), "SMem399", SN_NOWARN)
MakeNameEx(LocByName("Storm_401"), "SMemAlloc", SN_NOWARN)
MakeNameEx(LocByName("Storm_402"), "SMemDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_403"), "SMemFree", SN_NOWARN)
MakeNameEx(LocByName("Storm_404"), "SMemGetSize", SN_NOWARN)
MakeNameEx(LocByName("Storm_405"), "SMemReAlloc", SN_NOWARN)
MakeNameEx(LocByName("Storm_406"), "Storm406", SN_NOWARN)
MakeNameEx(LocByName("Storm_412"), "SMsgDispatchMessage", SN_NOWARN)
MakeNameEx(LocByName("Storm_413"), "SMsgDoMessageLoop", SN_NOWARN)
MakeNameEx(LocByName("Storm_414"), "SMsgRegisterCommand", SN_NOWARN)
MakeNameEx(LocByName("Storm_415"), "SMsgRegisterKeyDown", SN_NOWARN)
MakeNameEx(LocByName("Storm_416"), "SMsgRegisterKeyUp", SN_NOWARN)
MakeNameEx(LocByName("Storm_417"), "SMsgRegisterMessage", SN_NOWARN)
MakeNameEx(LocByName("Storm_418"), "SMsgPopRegisterState", SN_NOWARN)
MakeNameEx(LocByName("Storm_419"), "SMsgPushRegisterState", SN_NOWARN)
MakeNameEx(LocByName("Storm_420"), "SMsg420", SN_NOWARN)
MakeNameEx(LocByName("Storm_421"), "SRegLoadData", SN_NOWARN)
MakeNameEx(LocByName("Storm_422"), "SRegLoadString", SN_NOWARN)
MakeNameEx(LocByName("Storm_423"), "SRegLoadValue", SN_NOWARN)
MakeNameEx(LocByName("Storm_424"), "SRegSaveData", SN_NOWARN)
MakeNameEx(LocByName("Storm_425"), "SRegSaveString", SN_NOWARN)
MakeNameEx(LocByName("Storm_426"), "SRegSaveValue", SN_NOWARN)
MakeNameEx(LocByName("Storm_427"), "SRegGetBaseKey", SN_NOWARN)
MakeNameEx(LocByName("Storm_428"), "SRegDeleteValue", SN_NOWARN)
MakeNameEx(LocByName("Storm_429"), "SReg429", SN_NOWARN)
MakeNameEx(LocByName("Storm_430"), "SReg430", SN_NOWARN)
MakeNameEx(LocByName("Storm_431"), "STransBlt", SN_NOWARN)
MakeNameEx(LocByName("Storm_432"), "STransBltUsingMask", SN_NOWARN)
MakeNameEx(LocByName("Storm_433"), "STransCreateI", SN_NOWARN)
MakeNameEx(LocByName("Storm_434"), "STransDelete", SN_NOWARN)
MakeNameEx(LocByName("Storm_436"), "STransDuplicate", SN_NOWARN)
MakeNameEx(LocByName("Storm_437"), "STransIntersectDirtyArray", SN_NOWARN)
MakeNameEx(LocByName("Storm_438"), "STransInvertMask", SN_NOWARN)
MakeNameEx(LocByName("Storm_439"), "STransLoadI", SN_NOWARN)
MakeNameEx(LocByName("Storm_440"), "STransSetDirtyArrayInfo", SN_NOWARN)
MakeNameEx(LocByName("Storm_441"), "STransUpdateDirtyArray", SN_NOWARN)
MakeNameEx(LocByName("Storm_442"), "STransPointInMask", SN_NOWARN)
MakeNameEx(LocByName("Storm_443"), "STransCombineMasks", SN_NOWARN)
MakeNameEx(LocByName("Storm_444"), "STransCreateI", SN_NOWARN)
MakeNameEx(LocByName("Storm_445"), "STransCreateE", SN_NOWARN)
MakeNameEx(LocByName("Storm_446"), "STrans446", SN_NOWARN)
MakeNameEx(LocByName("Storm_447"), "STransLoadE", SN_NOWARN)
MakeNameEx(LocByName("Storm_451"), "SVidDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_452"), "SVidGetSize", SN_NOWARN)
MakeNameEx(LocByName("Storm_453"), "SVidInitialize", SN_NOWARN)
MakeNameEx(LocByName("Storm_454"), "SVidPlayBegin", SN_NOWARN)
MakeNameEx(LocByName("Storm_455"), "SVidPlayBeginFromMemory", SN_NOWARN)
MakeNameEx(LocByName("Storm_456"), "SVidPlayContinue", SN_NOWARN)
MakeNameEx(LocByName("Storm_457"), "SVidPlayContinueSingle", SN_NOWARN)
MakeNameEx(LocByName("Storm_458"), "SVidPlayEnd", SN_NOWARN)
MakeNameEx(LocByName("Storm_459"), "SVidSetVolume", SN_NOWARN)
MakeNameEx(LocByName("Storm_460"), "Storm460", SN_NOWARN)
MakeNameEx(LocByName("Storm_461"), "SErrDisplayError", SN_NOWARN)
MakeNameEx(LocByName("Storm_462"), "SErrGetErrorStr", SN_NOWARN)
MakeNameEx(LocByName("Storm_463"), "SErrGetLastError", SN_NOWARN)
MakeNameEx(LocByName("Storm_464"), "SErrRegisterMessageSource", SN_NOWARN)
MakeNameEx(LocByName("Storm_465"), "SErrSetLastError", SN_NOWARN)
MakeNameEx(LocByName("Storm_466"), "SErrReportNamedResourceLeak", SN_NOWARN)
MakeNameEx(LocByName("Storm_467"), "SErrReportResourceLeak", SN_NOWARN)
MakeNameEx(LocByName("Storm_468"), "SErrSuppressErrors", SN_NOWARN)
MakeNameEx(LocByName("Storm_469"), "SErrRegisterHandler", SN_NOWARN)
MakeNameEx(LocByName("Storm_470"), "SErrUnregisterHandler", SN_NOWARN)
MakeNameEx(LocByName("Storm_471"), "Storm471", SN_NOWARN)
MakeNameEx(LocByName("Storm_472"), "SCmdGetBool", SN_NOWARN)
MakeNameEx(LocByName("Storm_473"), "SCmdGetNum", SN_NOWARN)
MakeNameEx(LocByName("Storm_474"), "SCmdGetString", SN_NOWARN)
MakeNameEx(LocByName("Storm_475"), "SCmdProcess", SN_NOWARN)
MakeNameEx(LocByName("Storm_476"), "SCmdRegisterArgList", SN_NOWARN)
MakeNameEx(LocByName("Storm_477"), "SCmdRegisterArgument", SN_NOWARN)
MakeNameEx(LocByName("Storm_478"), "SCmdStringExists", SN_NOWARN)
MakeNameEx(LocByName("Storm_479"), "SCmdProcessCommandLine", SN_NOWARN)
MakeNameEx(LocByName("Storm_480"), "Ordinal480", SN_NOWARN)
MakeNameEx(LocByName("Storm_481"), "SMemFindNextBlock", SN_NOWARN)
MakeNameEx(LocByName("Storm_482"), "SMemFindNextHeap", SN_NOWARN)
MakeNameEx(LocByName("Storm_483"), "SMemGetHeapByCaller", SN_NOWARN)
MakeNameEx(LocByName("Storm_484"), "SMemGetHeapByPtr", SN_NOWARN)
MakeNameEx(LocByName("Storm_485"), "SMemHeapAlloc", SN_NOWARN)
MakeNameEx(LocByName("Storm_486"), "SMemHeapCreate", SN_NOWARN)
MakeNameEx(LocByName("Storm_487"), "SMemHeapDestroy", SN_NOWARN)
MakeNameEx(LocByName("Storm_488"), "SMemHeapFree", SN_NOWARN)
MakeNameEx(LocByName("Storm_489"), "SMemHeapRealloc", SN_NOWARN)
MakeNameEx(LocByName("Storm_490"), "SMemHeapSize", SN_NOWARN)
MakeNameEx(LocByName("Storm_491"), "SMemCopy", SN_NOWARN)
MakeNameEx(LocByName("Storm_492"), "SMemFill", SN_NOWARN)
MakeNameEx(LocByName("Storm_493"), "SMemMove", SN_NOWARN)
MakeNameEx(LocByName("Storm_494"), "SMemZero", SN_NOWARN)
MakeNameEx(LocByName("Storm_495"), "SMemCmp", SN_NOWARN)
MakeNameEx(LocByName("Storm_496"), "SMem496", SN_NOWARN)
MakeNameEx(LocByName("Storm_497"), "SMemDumpState", SN_NOWARN)
MakeNameEx(LocByName("Storm_498"), "Ordinal498", SN_NOWARN)
MakeNameEx(LocByName("Storm_501"), "SStrCopy", SN_NOWARN)
MakeNameEx(LocByName("Storm_502"), "SStrHash", SN_NOWARN)
MakeNameEx(LocByName("Storm_503"), "SStrNCat", SN_NOWARN)
MakeNameEx(LocByName("Storm_504"), "SStrTokenize", SN_NOWARN)
MakeNameEx(LocByName("Storm_505"), "SStrPack", SN_NOWARN)
MakeNameEx(LocByName("Storm_506"), "SStrLen", SN_NOWARN)
MakeNameEx(LocByName("Storm_507"), "SStrDup", SN_NOWARN)
MakeNameEx(LocByName("Storm_508"), "SStrCmp", SN_NOWARN)
MakeNameEx(LocByName("Storm_509"), "SStrCmpI", SN_NOWARN)
MakeNameEx(LocByName("Storm_510"), "SStrUpper", SN_NOWARN)
MakeNameEx(LocByName("Storm_511"), "SMsgBreakHandlerChain", SN_NOWARN)
MakeNameEx(LocByName("Storm_512"), "SMsgUnregisterCommand", SN_NOWARN)
MakeNameEx(LocByName("Storm_513"), "SMsgUnregisterKeyDown", SN_NOWARN)
MakeNameEx(LocByName("Storm_514"), "SMsgUnregisterKeyUp", SN_NOWARN)
MakeNameEx(LocByName("Storm_515"), "SMsgUnregisterMessage", SN_NOWARN)
MakeNameEx(LocByName("Storm_516"), "SMsgGetDispatcher", SN_NOWARN)
MakeNameEx(LocByName("Storm_517"), "SMsgSetDefaultWindow", SN_NOWARN)
MakeNameEx(LocByName("Storm_518"), "SMsgGetDefaultWindow", SN_NOWARN)
MakeNameEx(LocByName("Storm_519"), "SMsg519", SN_NOWARN)
MakeNameEx(LocByName("Storm_521"), "SRgn521", SN_NOWARN)
MakeNameEx(LocByName("Storm_523"), "SRgn523", SN_NOWARN)
MakeNameEx(LocByName("Storm_524"), "SRgnCreateRegion", SN_NOWARN)
MakeNameEx(LocByName("Storm_525"), "SRgnDeleteRegion", SN_NOWARN)
MakeNameEx(LocByName("Storm_527"), "SRgn527", SN_NOWARN)
MakeNameEx(LocByName("Storm_528"), "SRgn528i", SN_NOWARN)
MakeNameEx(LocByName("Storm_529"), "SRgn529i", SN_NOWARN)
MakeNameEx(LocByName("Storm_530"), "SRgn530i", SN_NOWARN)
MakeNameEx(LocByName("Storm_531"), "SRgn531i", SN_NOWARN)
MakeNameEx(LocByName("Storm_532"), "SRgn532i", SN_NOWARN)
MakeNameEx(LocByName("Storm_533"), "SRgn533i", SN_NOWARN)
MakeNameEx(LocByName("Storm_534"), "SRgn534", SN_NOWARN)
MakeNameEx(LocByName("Storm_535"), "SRgn535f", SN_NOWARN)
MakeNameEx(LocByName("Storm_536"), "SRgn536f", SN_NOWARN)
MakeNameEx(LocByName("Storm_537"), "SRgn537f", SN_NOWARN)
MakeNameEx(LocByName("Storm_538"), "SRgn538f", SN_NOWARN)
MakeNameEx(LocByName("Storm_539"), "SRgn539f", SN_NOWARN)
MakeNameEx(LocByName("Storm_540"), "SRgn540f", SN_NOWARN)
MakeNameEx(LocByName("Storm_541"), "SLogClose", SN_NOWARN)
MakeNameEx(LocByName("Storm_542"), "SLogCreate", SN_NOWARN)
MakeNameEx(LocByName("Storm_543"), "SLog543", SN_NOWARN)
MakeNameEx(LocByName("Storm_544"), "SLogDump", SN_NOWARN)
MakeNameEx(LocByName("Storm_545"), "SLogFlush", SN_NOWARN)
MakeNameEx(LocByName("Storm_546"), "SLogFlushAll", SN_NOWARN)
MakeNameEx(LocByName("Storm_547"), "SLogPend", SN_NOWARN)
MakeNameEx(LocByName("Storm_548"), "SLogWrite", SN_NOWARN)
MakeNameEx(LocByName("Storm_549"), "SLog549", SN_NOWARN)
MakeNameEx(LocByName("Storm_550"), "SLogCriticalLog", SN_NOWARN)
MakeNameEx(LocByName("Storm_551"), "SCompCompress", SN_NOWARN)
MakeNameEx(LocByName("Storm_552"), "SCompDecompress", SN_NOWARN)
MakeNameEx(LocByName("Storm_553"), "SLogVWrite", SN_NOWARN)
MakeNameEx(LocByName("Storm_554"), "Ordinal554", SN_NOWARN)
MakeNameEx(LocByName("Storm_555"), "Ordinal555", SN_NOWARN)
MakeNameEx(LocByName("Storm_556"), "Ordinal556", SN_NOWARN)
MakeNameEx(LocByName("Storm_557"), "Ordinal557", SN_NOWARN)
MakeNameEx(LocByName("Storm_558"), "Ordinal558", SN_NOWARN)
MakeNameEx(LocByName("Storm_559"), "Ordinal559", SN_NOWARN)
MakeNameEx(LocByName("Storm_560"), "Ordinal560", SN_NOWARN)
MakeNameEx(LocByName("Storm_561"), "SErrCheckDebugSymbolLibrary", SN_NOWARN)
MakeNameEx(LocByName("Storm_562"), "SErrDisplayErrorFmt", SN_NOWARN)
MakeNameEx(LocByName("Storm_563"), "SErrIsDisplayingError", SN_NOWARN)
MakeNameEx(LocByName("Storm_564"), "SErrPrepareAppFatal", SN_NOWARN)
MakeNameEx(LocByName("Storm_565"), "SErrSetLogTitleString", SN_NOWARN)
MakeNameEx(LocByName("Storm_566"), "SErrDisplayAppFatal", SN_NOWARN)
MakeNameEx(LocByName("Storm_567"), "SErrCatchUnhandledExceptions", SN_NOWARN)
MakeNameEx(LocByName("Storm_568"), "Storm568", SN_NOWARN)
MakeNameEx(LocByName("Storm_569"), "SStrChr", SN_NOWARN)
MakeNameEx(LocByName("Storm_570"), "SStrChrR", SN_NOWARN)
MakeNameEx(LocByName("Storm_571"), "SStrChr", SN_NOWARN)
MakeNameEx(LocByName("Storm_572"), "SStrChrR", SN_NOWARN)
MakeNameEx(LocByName("Storm_573"), "SStrToDouble", SN_NOWARN)
MakeNameEx(LocByName("Storm_574"), "SStrToFloat", SN_NOWARN)
MakeNameEx(LocByName("Storm_575"), "SStrToInt", SN_NOWARN)
MakeNameEx(LocByName("Storm_576"), "SStrToUnsigned", SN_NOWARN)
MakeNameEx(LocByName("Storm_577"), "SStrToInt64", SN_NOWARN)
MakeNameEx(LocByName("Storm_578"), "SStrVPrintf", SN_NOWARN)
MakeNameEx(LocByName("Storm_579"), "SStrLower", SN_NOWARN)
MakeNameEx(LocByName("Storm_580"), "SStrHash64", SN_NOWARN)
MakeNameEx(LocByName("Storm_581"), "SStrPrintf", SN_NOWARN)
MakeNameEx(LocByName("Storm_582"), "SDrawSetClientRect", SN_NOWARN)
MakeNameEx(LocByName("Storm_583"), "SDrawGetClientRect", SN_NOWARN)
MakeNameEx(LocByName("Storm_584"), "SStrStrI", SN_NOWARN)
MakeNameEx(LocByName("Storm_585"), "SStrStrI", SN_NOWARN)
MakeNameEx(LocByName("Storm_586"), "SStrStr", SN_NOWARN)
MakeNameEx(LocByName("Storm_587"), "SStrStr", SN_NOWARN)
MakeNameEx(LocByName("Storm_588"), "SNet588", SN_NOWARN)
MakeNameEx(LocByName("Storm_601"), "SBigAdd", SN_NOWARN)
MakeNameEx(LocByName("Storm_602"), "SBigAnd", SN_NOWARN)
MakeNameEx(LocByName("Storm_603"), "SBigCompare", SN_NOWARN)
MakeNameEx(LocByName("Storm_604"), "SBigCopy", SN_NOWARN)
MakeNameEx(LocByName("Storm_605"), "SBigDec", SN_NOWARN)
MakeNameEx(LocByName("Storm_606"), "SBigDel", SN_NOWARN)
MakeNameEx(LocByName("Storm_607"), "SBigDiv", SN_NOWARN)
MakeNameEx(LocByName("Storm_608"), "SBigFindPrime", SN_NOWARN)
MakeNameEx(LocByName("Storm_609"), "SBigFromBinary", SN_NOWARN)
MakeNameEx(LocByName("Storm_610"), "SBigFromStr", SN_NOWARN)
MakeNameEx(LocByName("Storm_611"), "SBigFromStream", SN_NOWARN)
MakeNameEx(LocByName("Storm_612"), "SBigFromUnsigned", SN_NOWARN)
MakeNameEx(LocByName("Storm_613"), "SBigGcd", SN_NOWARN)
MakeNameEx(LocByName("Storm_614"), "SBigInc", SN_NOWARN)
MakeNameEx(LocByName("Storm_615"), "SBigInvMod", SN_NOWARN)
MakeNameEx(LocByName("Storm_616"), "SBigIsEven", SN_NOWARN)
MakeNameEx(LocByName("Storm_617"), "SBigIsOdd", SN_NOWARN)
MakeNameEx(LocByName("Storm_618"), "SBigIsOne", SN_NOWARN)
MakeNameEx(LocByName("Storm_619"), "SBigIsPrime", SN_NOWARN)
MakeNameEx(LocByName("Storm_620"), "SBigIsZero", SN_NOWARN)
MakeNameEx(LocByName("Storm_621"), "SBigMod", SN_NOWARN)
MakeNameEx(LocByName("Storm_622"), "SBigMul", SN_NOWARN)
MakeNameEx(LocByName("Storm_623"), "SBigMulMod", SN_NOWARN)
MakeNameEx(LocByName("Storm_624"), "SBigNew", SN_NOWARN)
MakeNameEx(LocByName("Storm_625"), "SBigNot", SN_NOWARN)
MakeNameEx(LocByName("Storm_626"), "SBigOr", SN_NOWARN)
MakeNameEx(LocByName("Storm_627"), "SBigPow", SN_NOWARN)
MakeNameEx(LocByName("Storm_628"), "SBigPowMod", SN_NOWARN)
MakeNameEx(LocByName("Storm_629"), "SBigRand", SN_NOWARN)
MakeNameEx(LocByName("Storm_630"), "SBigSet2Exp", SN_NOWARN)
MakeNameEx(LocByName("Storm_631"), "SBigSetOne", SN_NOWARN)
MakeNameEx(LocByName("Storm_632"), "SBigSetZero", SN_NOWARN)
MakeNameEx(LocByName("Storm_633"), "SBigShl", SN_NOWARN)
MakeNameEx(LocByName("Storm_634"), "SBigShr", SN_NOWARN)
MakeNameEx(LocByName("Storm_635"), "SBigSquare", SN_NOWARN)
MakeNameEx(LocByName("Storm_636"), "SBigSub", SN_NOWARN)
MakeNameEx(LocByName("Storm_637"), "SBigToBinaryArray", SN_NOWARN)
MakeNameEx(LocByName("Storm_638"), "SBigToBinaryBuffer", SN_NOWARN)
MakeNameEx(LocByName("Storm_639"), "SBigToBinaryPtr", SN_NOWARN)
MakeNameEx(LocByName("Storm_640"), "SBigToStrArray", SN_NOWARN)
MakeNameEx(LocByName("Storm_641"), "SBigToStrBuffer", SN_NOWARN)
MakeNameEx(LocByName("Storm_642"), "SBigToStrPtr", SN_NOWARN)
MakeNameEx(LocByName("Storm_643"), "SBigToStreamArray", SN_NOWARN)
MakeNameEx(LocByName("Storm_644"), "SBigToStreamBuffer", SN_NOWARN)
MakeNameEx(LocByName("Storm_645"), "SBigToStreamPtr", SN_NOWARN)
MakeNameEx(LocByName("Storm_646"), "SBigToUnsigned", SN_NOWARN)
MakeNameEx(LocByName("Storm_647"), "SBigXor", SN_NOWARN)
MakeNameEx(LocByName("Storm_901"), "SUniConvertUTF16to8Len", SN_NOWARN)
MakeNameEx(LocByName("Storm_902"), "SUniConvertUTF16to8", SN_NOWARN)
MakeNameEx(LocByName("Storm_903"), "SUniConvertUTF8to16Len", SN_NOWARN)
MakeNameEx(LocByName("Storm_904"), "SUniConvertUTF8to16", SN_NOWARN)
MakeNameEx(LocByName("Storm_905"), "SUniS905", SN_NOWARN)
MakeNameEx(LocByName("Storm_906"), "SUniS906", SN_NOWARN)
MakeNameEx(LocByName("Storm_907"), "SUniFindAfterUTF8Chr", SN_NOWARN)
MakeNameEx(LocByName("Storm_908"), "SUniFindUTF8ChrStart", SN_NOWARN)
MakeNameEx(LocByName("Storm_909"), "SUniConvertUTF16To909", SN_NOWARN)
MakeNameEx(LocByName("Storm_910"), "SUniConvertUTF16To910", SN_NOWARN)
MakeNameEx(LocByName("Storm_911"), "SUniConvertUTF16To911", SN_NOWARN)
MakeNameEx(LocByName("Storm_912"), "SUniConvert912", SN_NOWARN)
MakeNameEx(LocByName("Storm_913"), "SUniConvert913", SN_NOWARN)
MakeNameEx(LocByName("Storm_914"), "SUniConvert914", SN_NOWARN)
MakeNameEx(LocByName("Storm_915"), "SUniConvertUTF8ToWin", SN_NOWARN)
SetType(LocByName("SNetCreateGame"), "BOOL __stdcall SNetCreateGame(const char *pszGameName, const char *pszGamePassword, const char *pszGameStatString, DWORD dwGameType, char *GameTemplateData, int GameTemplateSize, int playerCount, char *creatorName, char *a11, int *playerID)")
SetType(LocByName("SNetDestroy"), "BOOL __stdcall SNetDestroy()")
SetType(LocByName("SNetEnumProviders"), "BOOL __stdcall SNetEnumProviders(int (__stdcall *callback)(DWORD, DWORD, DWORD, DWORD), int mincaps)")
SetType(LocByName("SNetEnumGames"), "BOOL __stdcall SNetEnumGames(int (__stdcall *callback)(DWORD, DWORD, DWORD), int *hintnextcall)")
SetType(LocByName("SNetDropPlayer"), "BOOL __stdcall SNetDropPlayer(int playerid, DWORD flags)")
SetType(LocByName("SNetGetGameInfo"), "BOOL __stdcall SNetGetGameInfo(int type, void *dst, size_t length, size_t *byteswritten)")
SetType(LocByName("SNetGetNumPlayers"), "BOOL __stdcall SNetGetNumPlayers(int *firstplayerid, int *lastplayerid, int *activeplayers)")
SetType(LocByName("SNetGetOwnerTurnsWaiting"), "bool __stdcall SNetGetOwnerTurnsWaiting(int *)")
SetType(LocByName("SNetGetPlayerCaps"), "BOOL __stdcall SNetGetPlayerCaps(char playerid, PCAPS playerCaps)")
SetType(LocByName("SNetGetPlayerName"), "BOOL __stdcall SNetGetPlayerName(int playerid, char *buffer, size_t buffersize)")
SetType(LocByName("SNetGetProviderCaps"), "BOOL __stdcall SNetGetProviderCaps(PCAPS providerCaps)")
SetType(LocByName("SNetGetTurnsInTransit"), "BOOL __stdcall SNetGetTurnsInTransit(int *turns)")
SetType(LocByName("SNetInitializeDevice"), "BOOL __stdcall SNetInitializeDevice(int a1, int a2, int a3, int a4, int *a5)")
SetType(LocByName("SNetInitializeProvider"), "BOOL __stdcall SNetInitializeProvider(DWORD providerName, client_info *gameClientInfo, user_info *userData, battle_info *bnCallbacks, module_info *moduleData)")
SetType(LocByName("SNetJoinGame"), "BOOL __stdcall SNetJoinGame(int id, char *gameName, char *gamePassword, char *playerName, char *userStats, int *playerid)")
SetType(LocByName("SNetLeaveGame"), "BOOL __stdcall SNetLeaveGame(int type)")
SetType(LocByName("SNetPerformUpgrade"), "BOOL __stdcall SNetPerformUpgrade(DWORD *upgradestatus)")
SetType(LocByName("SNetReceiveMessage"), "BOOL __stdcall SNetReceiveMessage(int *senderplayerid, char **data, int *databytes)")
SetType(LocByName("SNetReceiveTurns"), "BOOL __stdcall SNetReceiveTurns(int a1, int arraysize, char **arraydata, unsigned int *arraydatabytes, DWORD *arrayplayerstatus)")
SetType(LocByName("SNetRegisterEventHandler"), "HANDLE __stdcall SNetRegisterEventHandler(int type, void (__stdcall *sEvent)(PS_EVT))")
SetType(LocByName("SNetSelectGame"), "int __stdcall SNetSelectGame(int a1, int a2, int a3, int a4, int a5, int *playerid)")
SetType(LocByName("SNetSendMessage"), "BOOL __stdcall SNetSendMessage(int playerID, void *data, size_t databytes)")
SetType(LocByName("SNetSendTurn"), "BOOL __stdcall SNetSendTurn(char *data, size_t databytes)")
SetType(LocByName("SNetSetGameMode"), "BOOL __stdcall SNetSetGameMode(DWORD modeFlags, bool makePublic)")
SetType(LocByName("SNetEnumGamesEx"), "BOOL __stdcall SNetEnumGamesEx(int a1, int a2, int (__fastcall *callback)(DWORD, DWORD, DWORD), int *hintnextcall)")
SetType(LocByName("SNetSendServerChatCommand"), "BOOL __stdcall SNetSendServerChatCommand(const char *command)")
SetType(LocByName("SNetDisconnectAll"), "BOOL __stdcall SNetDisconnectAll(DWORD flags)")
SetType(LocByName("SNetCreateLadderGame"), "BOOL __stdcall SNetCreateLadderGame(const char *pszGameName, const char *pszGamePassword, const char *pszGameStatString, DWORD dwGameType, DWORD dwGameLadderType, DWORD dwGameModeFlags, char *GameTemplateData, int GameTemplateSize, int playerCount, char *creatorName, char *a11, int *playerID)")
SetType(LocByName("SNetReportGameResult"), "BOOL __stdcall SNetReportGameResult(unsigned a1, int size, int *results, const char* headerInfo, const char* detailInfo)")
SetType(LocByName("SNetSendLeagueCommand"), "int __stdcall SNetSendLeagueCommand(char *cmd, char *callback)")
SetType(LocByName("SNetSendReplayPath"), "int __stdcall SNetSendReplayPath(int a1, int a2, char *replayPath)")
SetType(LocByName("SNetGetLeagueName"), "int __stdcall SNetGetLeagueName(int leagueID)")
SetType(LocByName("SNetGetPlayerNames"), "BOOL __stdcall SNetGetPlayerNames(char **names)")
SetType(LocByName("SNetLeagueLogout"), "int __stdcall SNetLeagueLogout(char *bnetName)")
SetType(LocByName("SNetGetLeaguePlayerName"), "int __stdcall SNetGetLeaguePlayerName(char *curPlayerLeageName, size_t nameSize)")
SetType(LocByName("SDlgDefDialogProc"), "HGDIOBJ __stdcall SDlgDefDialogProc(HWND hDlg, signed int DlgType, HDC textLabel, HWND hWnd)")
SetType(LocByName("SDlgDialogBoxIndirectParam"), "HANDLE __stdcall SDlgDialogBoxIndirectParam(HMODULE hModule, LPCSTR lpName, HWND hWndParent, LPVOID lpParam, LPARAM lParam)")
SetType(LocByName("SDlgEndDialog"), "BOOL __stdcall SDlgEndDialog(HWND hDlg, HANDLE nResult)")
SetType(LocByName("SDlgSetControlBitmaps"), "BOOL __stdcall SDlgSetControlBitmaps(HWND parentwindow, int *id, int a3, char *buffer2, char *buffer, int flags, int mask)")
SetType(LocByName("SDlgBltToWindowE"), "BOOL __stdcall SDlgBltToWindowE(HWND hWnd, HRGN a2, char *a3, int a4, void *buffer, RECT *rct, SIZE *size, int a8, int a9, DWORD rop)")
SetType(LocByName("SDlgSetBitmapE"), "BOOL __stdcall SDlgSetBitmapE(HWND hWnd, int a2, char *src, int mask1, int flags, int a6, int a7, int width, int a9, int mask2)")
SetType(LocByName("Ordinal224"), "int __stdcall Ordinal224(int a1)")
SetType(LocByName("SFileCloseArchive"), "BOOL __stdcall SFileCloseArchive(HANDLE hArchive)")
SetType(LocByName("SFileCloseFile"), "BOOL __stdcall SFileCloseFile(HANDLE hFile)")
SetType(LocByName("SFileDdaBeginEx"), "BOOL __stdcall SFileDdaBeginEx(HANDLE directsound, DWORD flags, DWORD mask, unsigned __int32 lDistanceToMove, signed __int32 volume, signed int a6, int a7)")
SetType(LocByName("SFileDdaDestroy"), "BOOL __stdcall SFileDdaDestroy()")
SetType(LocByName("SFileDdaEnd"), "BOOL __stdcall SFileDdaEnd(HANDLE directsound)")
SetType(LocByName("SFileDdaGetPos"), "BOOL __stdcall SFileDdaGetPos(HANDLE directsound, int a2, int a3)")
SetType(LocByName("SFileDdaInitialize"), "BOOL __stdcall SFileDdaInitialize(HANDLE directsound)")
SetType(LocByName("SFileDdaSetVolume"), "BOOL __stdcall SFileDdaSetVolume(HANDLE directsound, signed int bigvolume, signed int volume)")
SetType(LocByName("SFileDestroy"), "BOOL __stdcall SFileDestroy()")
SetType(LocByName("SFileGetFileArchive"), "BOOL __stdcall SFileGetFileArchive(HANDLE hFile, HANDLE archive)")
SetType(LocByName("SFileGetFileSize"), "LONG __stdcall SFileGetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh)")
SetType(LocByName("SFileOpenArchive"), "BOOL __stdcall SFileOpenArchive(const char *szMpqName, DWORD dwPriority, DWORD dwFlags, HANDLE *phMpq)")
SetType(LocByName("SFileOpenFile"), "BOOL __stdcall SFileOpenFile(const char *filename, HANDLE *phFile)")
SetType(LocByName("SFileOpenFileEx"), "BOOL __stdcall SFileOpenFileEx(HANDLE hMpq, const char *szFileName, DWORD dwSearchScope, HANDLE *phFile)")
SetType(LocByName("SFileReadFile"), "BOOL __stdcall SFileReadFile(HANDLE hFile, void *buffer, DWORD nNumberOfBytesToRead, DWORD *read, LONG lpDistanceToMoveHigh)")
SetType(LocByName("SFileSetLocale"), "void __stdcall SFileSetLocale(LCID lcLocale)")
SetType(LocByName("SFileSetIoErrorMode"), "BOOL __stdcall SFileSetIoErrorMode(int mode, BOOL (__stdcall *callback)(char*,int,int) )")
SetType(LocByName("SFileGetArchiveName"), "BOOL __stdcall SFileGetArchiveName(HANDLE hArchive, char *name, int length)")
SetType(LocByName("SFileGetFileName"), "BOOL __stdcall SFileGetFileName(HANDLE hFile, char *buffer, int length)")
SetType(LocByName("SFileLoadFile"), "BOOL __stdcall SFileLoadFile(char *filename, void *buffer, int buffersize, int a4, int a5)")
SetType(LocByName("SFileUnloadFile"), "BOOL __stdcall SFileUnloadFile(HANDLE hFile)")
SetType(LocByName("SFileLoadFileEx"), "BOOL __stdcall SFileLoadFileEx(void *hArchive, char *filename, int a3, int a4, int a5, DWORD searchScope, struct _OVERLAPPED *lpOverlapped)")
SetType(LocByName("SBltROP3"), "BOOL __stdcall SBltROP3(void *lpDstBuffer, void *lpSrcBuffer, int width, int height, int a5, int a6, int a7, DWORD rop)")
SetType(LocByName("SBltROP3Clipped"), "BOOL __stdcall SBltROP3Clipped(void *lpDstBuffer, RECT *lpDstRect, POINT *lpDstPt, int a4, void *lpSrcBuffer, RECT *lpSrcRect, POINT *lpSrcPt, int a8, int a9, DWORD rop)")
SetType(LocByName("SBmpDecodeImage"), "BOOL __stdcall SBmpDecodeImage(DWORD dwImgType, void *pSrcBuffer, DWORD dwSrcBuffersize, PALETTEENTRY *pPalette, void *pDstBuffer, DWORD dwDstBuffersize, DWORD *pdwWidth, DWORD *pdwHeight, DWORD *pdwBpp)")
SetType(LocByName("SBmpLoadImage"), "BOOL __stdcall SBmpLoadImage(const char *pszFileName, PALETTEENTRY *pPalette, void *pBuffer, DWORD dwBuffersize, DWORD *pdwWidth, DWORD *dwHeight, DWORD *pdwBpp)")
SetType(LocByName("SBmpSaveImage"), "BOOL   __stdcall SBmpSaveImage(const char*, PALETTEENTRY*, void*, DWORD, DWORD, DWORD)")
SetType(LocByName("SBmpAllocLoadImage"), "HANDLE __stdcall SBmpAllocLoadImage(const char *fileName, PALETTEENTRY *palette, void **buffer, int *width, int *height, int unused6, int unused7, void *(__stdcall *allocFunction)(DWORD))")
SetType(LocByName("SCodeCompile"), "BOOL __stdcall SCodeCompile(char *directives1, char *directives2, char *loopstring, unsigned int maxiterations, unsigned int flags, HANDLE handle)")
SetType(LocByName("SCodeDelete"), "BOOL __stdcall SCodeDelete(HANDLE handle)")
SetType(LocByName("SCodeExecute"), "int  __stdcall SCodeExecute(HANDLE handle, int a2)")
SetType(LocByName("SDrawAutoInitialize"), "BOOL __stdcall SDrawAutoInitialize(HINSTANCE hInst, LPCSTR lpClassName, LPCSTR lpWindowName, WNDPROC pfnWndProc, int nMode, int nWidth, int nHeight, int nBits)")
SetType(LocByName("SDrawCaptureScreen"), "BOOL __stdcall SDrawCaptureScreen(const char *source)")
SetType(LocByName("SDrawGetFrameWindow"), "HWND __stdcall SDrawGetFrameWindow(HWND *sdraw_framewindow)")
SetType(LocByName("SDrawGetObjects"), "BOOL __stdcall SDrawGetObjects(LPDIRECTDRAW *ddInterface, LPDIRECTDRAWSURFACE *primarySurface, LPDIRECTDRAWSURFACE *surface2, LPDIRECTDRAWSURFACE *surface3, LPDIRECTDRAWSURFACE *backSurface, LPDIRECTDRAWPALETTE *ddPalette, HPALETTE *hPalette)")
SetType(LocByName("SDrawGetScreenSize"), "BOOL __stdcall SDrawGetScreenSize(DWORD *pdwWidth, DWORD *pdwHeight, DWORD *pdwBpp)")
SetType(LocByName("SDrawLockSurface"), "BOOL __stdcall SDrawLockSurface(int surfacenumber, RECT *lpDestRect, void **lplpSurface, int *lpPitch, int arg_unused)")
SetType(LocByName("SDrawManualInitialize"), "BOOL __stdcall SDrawManualInitialize(HWND hWnd, LPDIRECTDRAW ddInterface, LPDIRECTDRAWSURFACE primarySurface, LPDIRECTDRAWSURFACE surface2, LPDIRECTDRAWSURFACE surface3, LPDIRECTDRAWSURFACE backSurface, LPDIRECTDRAWPALETTE ddPalette, HPALETTE hPalette)")
SetType(LocByName("SDrawPostClose"), "BOOL __stdcall SDrawPostClose()")
SetType(LocByName("SDrawRealizePalette"), "BOOL __stdcall SDrawRealizePalette()")
SetType(LocByName("SDrawUnlockSurface"), "BOOL __stdcall SDrawUnlockSurface(int surfacenumber, void *lpSurface, int a3, RECT *lpRect)")
SetType(LocByName("SDrawUpdatePalette"), "BOOL __stdcall SDrawUpdatePalette(unsigned int firstentry, unsigned int numentries, PALETTEENTRY *pPalEntries, int a4)")
SetType(LocByName("SEvtDispatch"), "BOOL __stdcall SEvtDispatch(DWORD dwMessageID, DWORD dwFlags, int type, PS_EVT pEvent)")
SetType(LocByName("SGdiDeleteObject"), "BOOL __stdcall SGdiDeleteObject(HANDLE handle)")
SetType(LocByName("SGdiExtTextOut"), "BOOL __stdcall SGdiExtTextOut(int a1, int a2, int a3, int a4, unsigned int a8, signed int a6, signed int a7, const char *string, unsigned int arg20)")
SetType(LocByName("SGdiImportFont"), "BOOL __stdcall SGdiImportFont(HGDIOBJ handle, int windowsfont)")
SetType(LocByName("SGdiSelectObject"), "BOOL __stdcall SGdiSelectObject(int handle)")
SetType(LocByName("SGdiSetPitch"), "BOOL __stdcall SGdiSetPitch(int pitch)")
SetType(LocByName("Ordinal393"), "BOOL __stdcall Ordinal393(char *string, int, int)")
SetType(LocByName("SMemAlloc"), "void* __stdcall SMemAlloc(size_t amount, char *logfilename, int logline, char defaultValue)")
SetType(LocByName("SMemFree"), "BOOL __stdcall SMemFree(void *location, char *logfilename, int logline, char defaultValue)")
SetType(LocByName("SMemReAlloc"), "void* __stdcall SMemReAlloc(void *location, size_t amount, char *logfilename, int logline, char defaultValue)")
SetType(LocByName("SRegLoadData"), "BOOL __stdcall SRegLoadData(const char *keyname, const char *valuename, int size, LPBYTE lpData, BYTE flags, LPDWORD lpcbData)")
SetType(LocByName("SRegLoadString"), "BOOL __stdcall SRegLoadString(const char *keyname, const char *valuename, BYTE flags, char *buffer, size_t buffersize)")
SetType(LocByName("SRegLoadValue"), "BOOL __stdcall SRegLoadValue(const char *keyname, const char *valuename, BYTE flags, int *value)")
SetType(LocByName("SRegSaveData"), "BOOL __stdcall SRegSaveData(const char *keyname, const char *valuename, int size, BYTE *lpData, DWORD cbData)")
SetType(LocByName("SRegSaveString"), "BOOL __stdcall SRegSaveString(const char *keyname, const char *valuename, BYTE flags, char *string)")
SetType(LocByName("SRegSaveValue"), "BOOL __stdcall SRegSaveValue(const char *keyname, const char *valuename, BYTE flags, DWORD result)")
SetType(LocByName("SRegDeleteValue"), "BOOL __stdcall SRegDeleteValue(const char *keyname, const char *valuename, BYTE flags)")
SetType(LocByName("STransBlt"), "BOOL __stdcall STransBlt(void *lpSurface, int x, int y, int width, HANDLE hTrans)")
SetType(LocByName("STransBltUsingMask"), "BOOL __stdcall STransBltUsingMask(void *lpSurface, void *lpSource, int pitch, int width, HANDLE hTrans)")
SetType(LocByName("STransDelete"), "BOOL __stdcall STransDelete(HANDLE hTrans)")
SetType(LocByName("STransDuplicate"), "BOOL __stdcall STransDuplicate(HANDLE hTransSource, HANDLE hTransDest)")
SetType(LocByName("STransIntersectDirtyArray"), "BOOL __stdcall STransIntersectDirtyArray(HANDLE hTrans, char * dirtyarraymask, unsigned flags, HANDLE * phTransResult)")
SetType(LocByName("STransInvertMask"), "BOOL __stdcall STransInvertMask(HANDLE hTrans, HANDLE * phTransResult)")
SetType(LocByName("STransSetDirtyArrayInfo"), "BOOL __stdcall STransSetDirtyArrayInfo(int width, int height, int depth, int bits)")
SetType(LocByName("STransPointInMask"), "BOOL __stdcall STransPointInMask(HANDLE hTrans, int x, int y)")
SetType(LocByName("STransCombineMasks"), "BOOL __stdcall STransCombineMasks(HANDLE hTransA, HANDLE hTransB, int left, int top, int flags, HANDLE * phTransResult)")
SetType(LocByName("STransCreateE"), "BOOL __stdcall STransCreateE(void *pBuffer, int width, int height, int bpp, int a5, int bufferSize, HANDLE *phTransOut)")
SetType(LocByName("SVidDestroy"), "BOOL __stdcall SVidDestroy()")
SetType(LocByName("SVidGetSize"), "BOOL __stdcall SVidGetSize(HANDLE video, int width, int height, int zero)")
SetType(LocByName("SVidInitialize"), "BOOL __stdcall SVidInitialize(HANDLE video)")
SetType(LocByName("SVidPlayBegin"), "BOOL __stdcall SVidPlayBegin(char *filename, int arg4, int a3, int a4, int a5, int a6, HANDLE* video)")
SetType(LocByName("SVidPlayContinueSingle"), "BOOL __stdcall SVidPlayContinueSingle(HANDLE video, int a2, int a3)")
SetType(LocByName("SVidPlayEnd"), "BOOL __stdcall SVidPlayEnd(HANDLE video)")
SetType(LocByName("SErrDisplayError"), "BOOL __stdcall SErrDisplayError(DWORD dwErrMsg, const char *logfilename, int logline, const char *message, BOOL allowOption, int exitCode)")
SetType(LocByName("SErrGetErrorStr"), "BOOL __stdcall SErrGetErrorStr(DWORD dwErrCode, char *buffer, size_t bufferchars)")
SetType(LocByName("SErrGetLastError"), "DWORD __stdcall SErrGetLastError()")
SetType(LocByName("SErrSetLastError"), "void __stdcall SErrSetLastError(DWORD dwErrCode)")
SetType(LocByName("SErrSuppressErrors"), "void __stdcall SErrSuppressErrors(BOOL suppressErrors)")
SetType(LocByName("SMemCopy"), "void __stdcall SMemCopy(void *dest, const void *source, size_t size)")
SetType(LocByName("SMemFill"), "void __stdcall SMemFill(void *location, size_t length, char fillWith)")
SetType(LocByName("SMemZero"), "void __stdcall SMemZero(void *location, DWORD length)")
SetType(LocByName("SMemCmp"), "int  __stdcall SMemCmp(void *location1, void *location2, DWORD size)")
SetType(LocByName("SStrCopy"), "int   __stdcall SStrCopy(char *dest, const char *src, int max_length)")
SetType(LocByName("SStrHash"), "DWORD __stdcall SStrHash(const char *string, DWORD flags, DWORD Seed)")
SetType(LocByName("SStrNCat"), "int   __stdcall SStrNCat(char *dest, const char *src, DWORD max_length)")
SetType(LocByName("SStrLen"), "int __stdcall SStrLen(const char* string)")
SetType(LocByName("SStrCmp"), "int __stdcall SStrCmp(const char *string1, const char *string2, size_t size)")
SetType(LocByName("SStrCmpI"), "int __stdcall SStrCmpI(const char *string1, const char *string2, size_t size)")
SetType(LocByName("SStrUpper"), "char* __stdcall SStrUpper(char* string)")
SetType(LocByName("SRgn523"), "void __stdcall SRgn523(HANDLE hRgn, RECT *pRect, int a3, int a4)")
SetType(LocByName("SRgnCreateRegion"), "void __stdcall SRgnCreateRegion(HANDLE *hRgn, int a2)")
SetType(LocByName("SRgnDeleteRegion"), "void __stdcall SRgnDeleteRegion(HANDLE hRgn)")
SetType(LocByName("SRgn529i"), "void __stdcall SRgn529i(int handle, int a2, int a3)")
SetType(LocByName("SErrDisplayErrorFmt"), "BOOL SErrDisplayErrorFmt(DWORD dwErrMsg, const char *logfilename, int logline, BOOL allowOption, int exitCode, const char *format, ...)")
SetType(LocByName("SErrCatchUnhandledExceptions"), "void __stdcall SErrCatchUnhandledExceptions()")
SetType(LocByName("SStrChr"), "char* __stdcall SStrChr(const char *string, char c)")
SetType(LocByName("SStrChrR"), "char* __stdcall SStrChrR(const char *string, char c)")
SetType(LocByName("SStrVPrintf"), "size_t SStrVPrintf(char *dest, size_t size, const char *format, ...)")
SetType(LocByName("SBigDel"), "int __stdcall SBigDel(void *buffer)")
SetType(LocByName("SBigFromBinary"), "int __stdcall SBigFromBinary(void *buffer, const void *str, size_t size)")
SetType(LocByName("SBigNew"), "int __stdcall SBigNew(void **buffer)")
SetType(LocByName("SBigPowMod"), "int __stdcall SBigPowMod(void *buffer1, void *buffer2, int a3, int a4)")
SetType(LocByName("SBigToBinaryBuffer"), "int __stdcall SBigToBinaryBuffer(void *buffer, int length, int a3, int a4)")
SetType(LocByName("SDrawMessageBox"), "void __stdcall SDrawMessageBox(char *,char *,int)")
SetType(LocByName("SDrawDestroy"), "void __cdecl SDrawDestroy(void)")
SetType(LocByName("StormDestroy"), "bool __cdecl StormDestroy(void)")
SetType(LocByName("SFileSetBasePath"), "bool __stdcall SFileSetBasePath(char *)")
SetType(LocByName("SDrawRealizePalette"), "void __cdecl SDrawRealizePalette(void)")
SetType(LocByName("SVidPlayContinue"), "bool __cdecl SVidPlayContinue(void)")
SetType(LocByName("SNetUnregisterEventHandler"), "void * __stdcall SNetUnregisterEventHandler(int,void (__stdcall*)(struct _SNETEVENT *))")
SetType(LocByName("SNetSetBasePlayer"), "bool __stdcall SNetSetBasePlayer(int)")
SetType(LocByName("SFileSetFilePointer"), "int __stdcall SFileSetFilePointer(HANDLE,int,HANDLE,int)")